### ISSUE TITLE
Listing on Django Packages.

### ISSUE THREAD

**Issue by lovelydinosaur** [JamesRitchie/django-rest-framework-sav#1]
Whenever you're happy to make this public it'd be worth adding to [the REST framework grid on Django Packages](https://www.djangopackages.com/grids/g/django-rest-framework/).

:smile:

**Comment by JamesRitchie** [comment]
[Done](https://www.djangopackages.com/packages/p/djangorestframework-sav/). Thanks for noticing!

**Comment by lovelydinosaur** [comment]
:+1:
